### ISSUE TITLE
How to wire this up?

### ISSUE THREAD

**Issue by rico** [dgrubelic/vue-authorize#8]
I can't seem to find a way to hook this package up with my current setup.

First I tried with the setup in the readme - with some `console.log` statements added to the handlers, I copied the code to the main js file, to the router etc. - nothing.

So I tried compose something with the `vue-authorization` instance I already have and some of your source code - without any luck.

I have added the additional files to the gist:

- [Authorize](https://gist.github.com/rico/57b1b5a6af51ff20eee0c9ee4a6ed8e3#file-authorize-js)
- [Router](https://gist.github.com/rico/57b1b5a6af51ff20eee0c9ee4a6ed8e3#file-router-js)

Thanks again for your help, and let me know if I can sponser you a beer or how I can support your work. BTW. authentication works great!

**Comment by dgrubelic** [comment]
Hi @rico,

thanks for your support. For now, I don't really have any way of collecting donations, so, for now, you can just spread the word about my work. I'm glad you find it useful. 

About the problem, I see you haven't refined any permissions for roles. This is the problem.

Honestly, with all my focus on vue-authenticate, I haven't really had time to focus on vue-authorize library too. I should really take some time to rethink this logic and make a stable library for production usage.

**Comment by rico** [comment]
Hi @dgrubelic - thank you for your support. I got it going with your tip about the permissions.

You should definitely set up a channel for donations. At least for me, authorization is very important in all of my applications and there seems to be no real alternative to this library (`vue-auth` did not work when I tried it).

Therefore I think this is worth a few hours of work (I'll definitely support development). Just announce it as a perfect match for Laravel based API's when finished and you will have a very solid user base ;-)
